Genie DAG import scripts
knowledgesystems/cmo-pipelines pull request #1201
Opened 2024-10-31 16:58 UTC by callachennault

2025-01-15 20:44 UTC, callachennault commented on import-scripts/set_import_status.sh
I'm not sure if this script is totally needed, but if it doesn't exist and I have the dag call the update_process script directly then I need to set the properties file in the DAG. I can make that change, I just went with the pattern of the other tasks for now, where the properties filepath is set in the bash script.

2025-01-15 21:48 UTC, sheridancbio requested changes
review covers first file only, but most comments apply to all scripts
additional scripts will be reviewed in a second review.

2025-01-15 21:48 UTC, sheridancbio commented on import-scripts/clone_db_wrapper.sh
> +#!/bin/bash
I suggest a more specific filename because the scripts directory is such a big mix of scripts for all kinds of purposes. Perhaps : genie-import-airflow-task-clone-db.sh

2025-01-15 21:48 UTC, sheridancbio commented on import-scripts/clone_db_wrapper.sh
> +    echo "`date`: Unable to locate automation_env, exiting..."
probably better to spell out the entire filename which is unfound : 'automation_environment.sh'

2025-01-15 21:48 UTC, sheridancbio commented on import-scripts/clone_db_wrapper.sh
> +source $PORTAL_SCRIPTS_DIRECTORY/automation-environment.sh
because this filepath appears twice, we could have an environment variable for it:
AUTOMATION_ENVIRONMENT_SCRIPT_FILEPATH="$PORTAL_SCRIPTS_DIRECTORY/automation-environment.sh"
that would reduce the chance of the two references to the file getting out of sync.
This comment applies to the other files as well.

2025-01-15 21:48 UTC, sheridancbio commented on import-scripts/clone_db_wrapper.sh
> +# This file will be used throughout entire import job to determine directionality
I think this comment is out of date or misplaced?

2025-01-15 21:48 UTC, sheridancbio commented on import-scripts/clone_db_wrapper.sh
> +MANAGE_DATABASE_TOOL_PROPERTIES_FILEPATH="$PORTAL_SCRIPTS_DIRECTORY/airflowdb.properties"
this properties file is genie specific, and also is specific to managing the dataflow tools needed for clickhouse processing. I think the filename should include additional specification. Also, I do not think the file containing the database credentials should reside in the scripts directory. The more conventional location for a properties file such as that would be in /data/portal-cron/pipeline-credentials (or perhaps /data/portal-cron/git-repos/portal-configuration)

2025-01-15 21:48 UTC, sheridancbio commented on import-scripts/clone_db_wrapper.sh
> +current_production_database_color=$(sh $PORTAL_SCRIPTS_DIRECTORY/get_database_currently_in_production.sh $MANAGE_DATABASE_TOOL_PROPERTIES_FILEPATH)
To be consistent with usage above, the filepath to get_database_currently_in_production.sh should be stored in an environment variable rather than being constructed on the fly in this line.

2025-01-15 22:11 UTC, callachennault commented on import-scripts/clone_db_wrapper.sh
> +# This file will be used throughout entire import job to determine directionality
good catch, thanks!

2025-01-15 22:15 UTC, callachennault commented on import-scripts/clone_db_wrapper.sh
> +current_production_database_color=$(sh $PORTAL_SCRIPTS_DIRECTORY/get_database_currently_in_production.sh $MANAGE_DATABASE_TOOL_PROPERTIES_FILEPATH)
done!

2025-01-15 22:18 UTC, callachennault commented on import-scripts/clone_db_wrapper.sh
> +    echo "`date`: Unable to locate automation_env, exiting..."
done

2025-01-15 22:19 UTC, callachennault commented on import-scripts/clone_db_wrapper.sh
> +source $PORTAL_SCRIPTS_DIRECTORY/automation-environment.sh
done

2025-01-15 22:53 UTC, sheridancbio requested changes
additional issues found in remaining files (part 2 of review)

2025-01-15 22:53 UTC, sheridancbio commented on import-scripts/import_clickhouse.sh
> +#!/bin/bash
suggest filename such as genie-import-airflow-task-copy-to-clickhouse.sh

2025-01-15 22:53 UTC, sheridancbio commented on import-scripts/import_genie.sh
> +#!/bin/bash
suggest filename such as genie-import-airflow-task-update-studies.sh

2025-01-15 22:53 UTC, sheridancbio commented on import-scripts/set_import_status.sh
> +IMPORT_STATUS=$1
suggest filename such as genie-import-airflow-task-set-status.sh

2025-01-15 22:53 UTC, sheridancbio commented on import-scripts/setup_import.sh
> +#!/bin/bash
suggest filename such as genie-import-airflow-task-setup.sh

2025-01-15 23:01 UTC, callachennault commented on import-scripts/import_clickhouse.sh
> +CREATE_DERIVED_TABLES_IN_CLICKHOUSE_SQL_2_FILEPATH="$PORTAL_HOME/create_derived_clickhouse_tables/genie/materialized_views.sql"
Thanks for the explanation! I was a bit confused on the derived tables code/what exactly these filepaths are, meant to clarify with you when we met yesterday. Let me know if I can help with any of the changes

2025-01-15 23:04 UTC, callachennault commented on import-scripts/import_genie.sh
> +$JAVA_BINARY -Xmx64g $JAVA_IMPORTER_ARGS --update-study-data --portal genie-archive-portal --update-worksheet --notification-file "$genie_portal_notification_file" --oncotree-version $ONCOTREE_VERSIO
good catch - I updated the portal argument on the server and forgot to do it here. You're also right about the genie_portal_notification_file var, it's not set in this file - I'm not sure that I understand what this file is actually used for. In import-genie-data.sh it's used in this call - do you know what this does?

`    $JAVA_BINARY $JAVA_IMPORTER_ARGS --send-update-notification --portal genie-portal --notification-file "$genie_portal_notification_file"
`

2025-01-15 23:07 UTC, callachennault commented on import-scripts/import_genie.sh
> +tail -f $PORTAL_HOME/logs/genie-aws-importer.log &
I also wasn't sure if it would work, but this was the simplest solution I could think of to direct the importer logs to the Airflow logs UI. The tail exits when the script finishes. Other options I discussed with Avery could be changing the log4j file to a file location that Airflow would read from

2025-01-16 18:08 UTC, callachennault commented on import-scripts/import_genie.sh
> +IMPORTER=$1
It is used later in constructing the importer filename - I think @averyniceday wrote this bit - possibly to accommodate other importers in the future?

2025-01-23 22:58 UTC, callachennault commented on import-scripts/import_genie.sh
> +$JAVA_BINARY -Xmx64g $JAVA_IMPORTER_ARGS --update-study-data --portal genie-archive-portal --update-worksheet --notification-file "$genie_portal_notification_file" --oncotree-version $ONCOTREE_VERSIO
It looks like this file is used when sending the updated studies notification email. Since we can handle these notifications through Airflow, I removed the `--notification-file` argument from the import call.

2025-01-27 17:07 UTC, averyniceday commented on import-scripts/genie-airflow-set-import-status.sh
> +IMPORT_STATUS=$1
can we add a comment here about what this script does (esp. in the context of executed DAG)? I see that the referenced script is also called separately in another script.

2025-01-27 17:11 UTC, averyniceday commented on import-scripts/genie-airflow-clone-db.sh
> +echo "we are going to clone $source_database_color into $destination_database_color and then import into $destination_database_color"
maybe genericize this? 
```
Source DB: Blah
Destination DB: Blah
```

2025-01-27 17:11 UTC, averyniceday commented on import-scripts/genie-airflow-clone-db.sh
> +echo "we are going to clone $source_database_color into $destination_database_color and then import into $destination_database_color"
also, I'm assuming the tooling scripts we're calling also include sys.out logging

2025-01-27 17:15 UTC, averyniceday commented on import-scripts/genie-airflow-import-clickhouse.sh
> +
Maybe also include a generic logging as needed
```
Mysql Source/Dest
Clickhouse Source/Dest
```

2025-01-27 17:17 UTC, averyniceday commented on import-scripts/genie-airflow-import-sql.sh
> +echo "Importing with $IMPORTER_JAR_FILENAME"
add generic dest db logging too

2025-01-27 17:20 UTC, averyniceday approved these changes
Overall looks good for first release -- 

couple comments regarding logging messages, mostly just clarifying Source/Dest db. 

For future work/improvements, need to make sure server is inline with what the scripts expect (esp. in this SSHOperator mode of running)

Also suggest (maybe this is already in the DAG repo) -- adding a README.md for the DAG workflow and steps. What is "wrapper" logic versus tooling logic and expected frequency of updates/tweaks.

2025-01-27 21:20 UTC, callachennault commented on import-scripts/genie-airflow-set-import-status.sh
> +IMPORT_STATUS=$1
I left a comment above about this script. Let me know what you think
> I'm not sure if this script is totally needed, but if it doesn't exist and I have the dag call the update_process script directly then I need to set the properties file in the DAG. I can make that change, I just went with the pattern of the other tasks for now, where the properties filepath is set in the bash script.

2025-01-27 21:32 UTC, callachennault commented
thanks @averyniceday, responding below:

> For future work/improvements, need to make sure server is inline with what the scripts expect (esp. in this SSHOperator mode of running)

Can you elaborate on what you mean by this?

> Also suggest (maybe this is already in the DAG repo) -- adding a README.md for the DAG workflow and steps. What is "wrapper" logic versus tooling logic and expected frequency of updates/tweaks.

I'd prefer not to document the DAG steps because Airflow already generates a DAG diagram which will automatically reflect any changes to the tasks/task order. The tasks are also documented in the DAG file and in the scripts themselves. What do you mean by tooling logic?

2025-01-28 19:56 UTC, callachennault commented on import-scripts/genie-airflow-set-import-status.sh
> +IMPORT_STATUS=$1
I removed this script and changed the date to call the update_process script directly.

2025-01-29 22:05 UTC, sheridancbio commented on import-scripts/import_clickhouse.sh
> +CREATE_DERIVED_TABLES_IN_CLICKHOUSE_SQL_2_FILEPATH="$PORTAL_HOME/create_derived_clickhouse_tables/genie/materialized_views.sql"
I see these have been incorporated. I forget whether I did a PR already with the download scripts, but if not, we should get those into the cmo-pipelines repo soon.

2025-01-29 22:09 UTC, sheridancbio commented on import-scripts/import_genie.sh
> +IMPORTER=$1
I see it now

2025-01-29 22:11 UTC, sheridancbio commented on import-scripts/import_genie.sh
> +tail -f $PORTAL_HOME/logs/genie-aws-importer.log &
👍

2025-01-29 22:17 UTC, sheridancbio commented on import-scripts/import_genie.sh
> +$JAVA_BINARY -Xmx64g $JAVA_IMPORTER_ARGS --update-study-data --portal genie-archive-portal --update-worksheet --notification-file "$genie_portal_notification_file" --oncotree-version $ONCOTREE_VERSIO
It is ok if the notification file is defined in automation_environment. I do wonder about dropping it --- the notification file is written by the importer as it makes progress through the set of studies which were marked for import. Studies which are successfully imported appear in the notification file simply as the study stable id in a list. But studies which fail import with some kind of trapped exception inject a stacktrace into this file which is useful for the curation team. Maybe by dropping the argument for the notification file, no file will be written. But then I wonder how the curation team will know which of the study imports succeeded and which failed (or why).

I'll approve this PR ... but I think we should follow up on this point. We should be able to notify the curation team of success/failure on a study by study basis. I'd don't remember us having any airflow logic to do that.

2025-01-29 22:17 UTC, sheridancbio approved these changes

2025-04-11 19:19 UTC, merged