chain the cmo data import into the import wrapper
knowledgesystems/cmo-pipelines pull request #854
Opened 2021-06-17 19:17 UTC by sheridancbio

- this makes the dmp fetch independent of the dmp import
- the dmp fetch is launched each night at 00:30 (if yesterday's fetch or import is still running, it exits)
- the wrapper script now runs at 01:00 and goes through this sequence:
  - import cmo data (msk-automation)
  - wait for dmp fetch to be complete (the wait will be forcefully terminated at 23:30 and script will exit)
  - import dmp data
  - release the lock to allow tomorrow's dmp fetch to proceed if necessary
  - import pdx data
  - import msk-mind data
  - import msk-spectrum data

2021-06-17 19:37 UTC, averyniceday requested changes
Looks good to me but I wonder if we should cut our losses earlier. The script takes 11:30pm as the last acceptable import time but we've been operating under the assumption that they will end by around 10/11am. 

It's possible it will interfere with other imports we run through the day (or if it starts at 11pm, bleed into the next day). 

Additionally I think we also wanted to avoid restarting the portal during regular hours.

2021-06-17 20:39 UTC, averyniceday approved these changes

2021-06-17 20:49 UTC, sheridancbio commented
talking with @averyniceday just now, we came to a belief that we don't want the dmp imports happening too late in the day either. Our rule of thumb was that if the dmp imports were not expected to complete by 9am then we would skip over the import attempts. From the little schedule above, if the imports start by 7am, we would expect the dmp study imports to finish by 8:40 ... so we are going to put in logic which says "if we are not ready to go by 7am, then skip dmp imports for today". We have moved up the dmp fetching by an hour and a half (they will start at 00:30 rather than 02:00) and we are going to require that the cmo import script completes before the dmp imports starts. The good thing is that the dmp imports can start as soon as the cmo imports are done and the dmp fetches are done ... so fast fetches and a light cmo import should mean an earlier start than normal.

2021-06-18 16:50 UTC, averyniceday approved these changes

2021-06-18 19:01 UTC, sheridancbio commented
Latest changes are to swap the order of the dmp data import and the cmo data import. Also, we advance the start time for dmp fetches so that they start at 8pm. We expect these will end around 11pm and then next step in the wrapper script will be to run the dmp data imports. We expect those to last around 2 hours, so around 1am we expect the next step in the wrapper script to run ... which is the cmo data imports. Those will take however long they take (varies greatly) but afterwards the pdx, msk-mind, and spectrum imports happen. If the whole process is not complete by 8pm then the following day's import run is skipped.

2021-06-18 19:03 UTC, merged